ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'NETEASE_163';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'NETEASE_126';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'ICLOUD';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'YAHOO';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'ZOHO';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'ALIYUN';
