ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'AMAZON_WORKMAIL';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'FASTMAIL';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'AOL';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'GMX';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'MAILCOM';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'YANDEX';
ALTER TYPE "MailProvider" ADD VALUE IF NOT EXISTS 'CUSTOM_IMAP_SMTP';
