import { emailApi, groupApi, oauthApi } from '../../api';

export const emailsContract = {
  getList: emailApi.getList,
  getById: emailApi.getById,
  revealUnlock: emailApi.revealUnlock,
  revealSecrets: emailApi.revealSecrets,
  getStats: emailApi.getStats,
  create: emailApi.create,
  update: emailApi.update,
  delete: emailApi.delete,
  batchDelete: emailApi.batchDelete,
  import: emailApi.import,
  export: emailApi.export,
  viewMails: emailApi.viewMails,
  clearMailbox: emailApi.clearMailbox,
  deleteSelectedMails: emailApi.deleteSelectedMails,
  batchFetchMailboxes: emailApi.batchFetchMailboxes,
  batchClearMailbox: emailApi.batchClearMailbox,
  sendMail: emailApi.sendMail,
  getGroups: groupApi.getList,
  createGroup: groupApi.create,
  updateGroup: groupApi.update,
  deleteGroup: groupApi.delete,
  assignEmails: groupApi.assignEmails,
  removeEmails: groupApi.removeEmails,
  getProviderStatuses: oauthApi.getProviderStatuses,
  getAuthorizationStatus: oauthApi.getAuthorizationStatus,
  parseGoogleClientSecret: oauthApi.parseGoogleClientSecret,
  saveConfig: oauthApi.saveConfig,
  startAuthorization: oauthApi.startAuthorization,
};
